version: '3.8'

services:
  onix-landing:
    image: nginx:alpine
    container_name: onix_landing_server
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
    restart: always